export const LANDMARKS = [
  {
    name: "Christ the Redeemer",
    img: "photos/riodejaneiro.jpeg",
    continent: "South America",
    country: "Brazil",
    city: "Rio de Janeiro",
  },
  {
    name: "Machu Picchu",
    img: "photos/MachuPicchu.jpeg",
    continent: "South America",
    country: "Peru",
    city: "Cusco",
  },
  {
    name: "Eiffel Tower",
    img: "photos/paris.jpeg",
    continent: "Europe",
    country: "France",
    city: "Paris",
  },
  {
    name: "Louvre",
    img: "photos/paris2.avif",
    continent: "Europe",
    country: "France",
    city: "Paris",
  },
  {
    name: "Sydney Opera House",
    img: "photos/sydney.jpeg",
    continent: "Oceania",
    country: "Australia",
    city: "Sydney",
  },
  {
    name: "Great Wall",
    img: "photos/Beijing.jpeg",
    continent: "Asia",
    country: "China",
    city: "Beijing",
  },
  {
    name: "Taj Mahal",
    img: "photos/agra.avif",
    continent: "Asia",
    country: "India",
    city: "Agra",
  },
  {
    name: "Great Pyramids of Giza",
    img: "photos/cairo.jpeg",
    continent: "Africa",
    country: "Egypt",
    city: "Cairo",
  },
  {
    name: "Capadocia",
    img: "photos/capadocia.avif",
    continent: "Asia",
    country: "Turkey",
    city: "Capadocia",
  },
  {
    name: "Big ben",
    img: "photos/london.jpeg",
    continent: "Europe",
    country: "UK",
    city: "London",
  },
  {
    name: "Ferris Wheel",
    img: "photos/london2.avif",
    continent: "Europe",
    country: "UK",
    city: "London",
  },
  {
    name: "New York",
    img: "photos/newyork.jpeg",
    continent: "North America",
    country: "USA",
    city: "New York",
  },
  {
    name: "Colosseum",
    img: "photos/rome.jpeg",
    continent: "Europe",
    country: "Italy",
    city: "Rome",
  },
  {
    name: "Stonehenge",
    img: "photos/salisbury.avif",
    continent: "Europe",
    country: "UK",
    city: "Salisbury",
  },
  {
    name: "Azadi Tower",
    img: "photos/tehran.avif",
    continent: "Asia",
    country: "Iran",
    city: "Tehran",
  },
  {
    name: "Plaza De Toros",
    img: "photos/valencia.avif",
    continent: "Europe",
    country: "Spain",
    city: "Valencia",
  },
];

export const GEOGRAPHY_DATA = {
  Africa: {
    Egypt: [
      "Cairo",
      "Alexandria",
      "Giza",
      "Luxor",
      "Aswan",
      "Port Said",
      "Suez",
      "Mansoura",
      "Tanta",
      "Ismailia",
    ],
    Nigeria: [],
    Kenya: [],
    "South Africa": [],
    Ghana: [],
    Ethiopia: [],
    Morocco: [],
    Tanzania: [],
    Uganda: [],
    Senegal: [],
  },
  Asia: {
    China: [
      "Beijing",
      "Shanghai",
      "Chongqing",
      "Guangzhou",
      "Shenzhen",
      "Tianjin",
      "Wuhan",
      "Chengdu",
      "Xi'an",
      "Hangzhou",
    ],
    India: [
      "Delhi",
      "Mumbai",
      "Bangalore",
      "Hyderabad",
      "Chennai",
      "Kolkata",
      "Pune",
      "Jaipur",
      "Surat",
      "Agra",
    ],
    Iran: [
      "Tehran",
      "Mashhad",
      "Isfahan",
      "Karaj",
      "Shiraz",
      "Tabriz",
      "Qom",
      "Ahvaz",
      "Kermanshah",
      "Yazd",
    ],
    Turkey: [
      "Istanbul",
      "Ankara",
      "Izmir",
      "Bursa",
      "Antalya",
      "Konya",
      "Adana",
      "Gaziantep",
      "Sanliurfa",
      "Kayseri",
    ],
  },
  Europe: {
    France: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
    ],
    Italy: [
      "Rome",
      "Milan",
      "Naples",
      "Turin",
      "Palermo",
      "Genoa",
      "Bologna",
      "Florence",
      "Bari",
      "Catania",
    ],
    Spain: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Malaga",
      "Murcia",
      "Palma de Mallorca",
      "Bilbao",
      "Alicante",
    ],
    UK: [
      "London",
      "Birmingham",
      "Manchester",
      "Glasgow",
      "Liverpool",
      "Leeds",
      "Sheffield",
      "Edinburgh",
      "Bristol",
      "Nottingham",
    ],
  },
  "North America": {
    USA: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
    ],
    Canada: [],
    Mexico: [],
    Cuba: [],
    "Costa Rica": [],
  },
  "South America": {
    Brazil: [
      "São Paulo",
      "Rio de Janeiro",
      "Brasília",
      "Salvador",
      "Fortaleza",
      "Belo Horizonte",
      "Manaus",
      "Curitiba",
      "Recife",
      "Porto Alegre",
    ],
    Peru: [
      "Lima",
      "Arequipa",
      "Trujillo",
      "Chiclayo",
      "Piura",
      "Iquitos",
      "Cusco",
      "Huancayo",
      "Tacna",
      "Callao",
    ],
    Argentina: [],
    Chile: [],
    Colombia: [],
  },
  Oceania: {
    Australia: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Canberra",
      "Newcastle",
      "Wollongong",
      "Hobart",
    ],
    "Papua New Guinea": [],
    "New Zealand": [],
    Fiji: [],
    Samoa: [],
  },
};
